### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found, Datawig 0.1.12

### ISSUE THREAD

**Issue by anastasiiaplatovskikh** [awslabs/datawig#124]
Hi All,

I installed the latest (0.1.12) version of Datawig module. I've considered all the package requirements:

- scikit-learn[alldeps]==0.22.1
- typing==3.6.6
- pandas==0.25.3
- mxnet==1.4.0

But when I run the command "import datawig", I get the following error:

Traceback (most recent call last):
  File "C:/Users/PC/Desktop/python_ummd/venv/Lib/imputation.py", line 7, in <module>
    import datawig
  File "C:\Users\PC\Desktop\untitled1\venv\bin\lib\site-packages\datawig\__init__.py", line 2, in <module>
    from .column_encoders import CategoricalEncoder, BowEncoder, NumericalEncoder, SequentialEncoder
  File "C:\Users\PC\Desktop\untitled1\venv\bin\lib\site-packages\datawig\column_encoders.py", line 26, in <module>
    import mxnet as mx
  File "C:\Users\PC\Desktop\untitled1\venv\bin\lib\site-packages\mxnet\__init__.py", line 24, in <module>
    from .context import Context, current_context, cpu, gpu, cpu_pinned
  File "C:\Users\PC\Desktop\untitled1\venv\bin\lib\site-packages\mxnet\context.py", line 24, in <module>
    from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
  File "C:\Users\PC\Desktop\untitled1\venv\bin\lib\site-packages\mxnet\base.py", line 213, in <module>
    _LIB = _load_lib()
  File "C:\Users\PC\Desktop\untitled1\venv\bin\lib\site-packages\mxnet\base.py", line 204, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

I want to use SimpleImputer. I use Windows [Version 10.0.18363.836], Python 3.7, Pycharm  2020.1.1.

Could someone give me a hint by this issue?

Best regards,
Anastasiia

**Comment by TammoR** [comment]
HI Anastasiia,

I don't have a windows machine at my hands, so can't confirm but maybe using the same python bit-width as your dll will help, see here: https://github.com/apache/incubator-mxnet/issues/1740

Regards
Tammo

**Comment by anastasiiaplatovskikh** [comment]
> HI Anastasiia,
> 
> I don't have a windows machine at my hands, so can't confirm but maybe using the same python bit-width as your dll will help, see here: [apache/incubator-mxnet#1740](https://github.com/apache/incubator-mxnet/issues/1740)
> 
> Regards
> Tammo

Hi Tammo,

thank you very much for your reply. Can you please explain how can I find these dll files?

Best regards,
Anastasiia

**Comment by TammoR** [comment]
HI Anastasiia,

Can you try a different Python version, i.e. 32bit or 64bit Python?

**Comment by TammoR** [comment]
Closing because it's now discussed on stackoverflow:
https://stackoverflow.com/questions/61988217/error-module-datawig-0-1-12-in-python-3-7-7-oserror-winerror-126-the-specifi/62061604#62061604
