### ISSUE TITLE
Datawig: NotADirectoryError: [WinError 267] The directory name is invalid: '.\\Level 0: Cat Group'

### ISSUE THREAD

**Issue by TizianFusser** [awslabs/datawig#139]
Hi, thanks for the amazing library.

I am having an issue while running the complete() method.

````
import datawig
import pandas as pd

df = pd.read_csv('SpendCubeCleanNAN.csv', low_memory=False)

df_imp= datawig.SimpleImputer.complete(df)

df_imp.to_csv('SpendCubeCleanImpNN.csv')
````

Level 0: Cat Group is a column name in my dataset.

This is the output with the error traceback:

````

`C:\Users\Shadow\miniconda3\lib\site-packages\sklearn\utils\extmath.py:765: RuntimeWarning: invalid value encountered in true_divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
C:\Users\Shadow\miniconda3\lib\site-packages\sklearn\utils\extmath.py:706: RuntimeWarning: Degrees of freedom <= 0 for slice.
  result = op(x, *args, **kwargs)
[10:30:26] c:\jenkins\workspace\mxnet-tag\mxnet\src\operator\../common/utils.h:450: 
Storage type fallback detected:
operator = Concat
input storage types = [csr, default, ]
output storage types = [default, ]
params = {"num_args" : 2, "dim" : 1, }
context.dev_mask = cpu
The operator with default storage type will be dispatched for execution. You're seeing this warning message because the operator above is unable to process the given ndarrays with specified storage types, context and parameter. Temporary dense ndarrays are generated in order to execute the operator. This does not affect the correctness of the programme. You can set environment variable MXNET_STORAGE_FALLBACK_LOG_VERBOSE to 0 to suppress this warning.
Traceback (most recent call last):
  File "C:/Users/Shadow/PycharmProjects/Datawig/SimpleImpSpendCube.py", line 8, in <module>
    df_imp= datawig.SimpleImputer.complete(df)
  File "C:\Users\Shadow\miniconda3\lib\site-packages\datawig\simple_imputer.py", line 527, in complete
    calibrate=False)
  File "C:\Users\Shadow\miniconda3\lib\site-packages\datawig\simple_imputer.py", line 382, in fit
    output_path=self.output_path)
  File "C:\Users\Shadow\miniconda3\lib\site-packages\datawig\imputer.py", line 150, in __init__
    os.makedirs(self.output_path)
  File "C:\Users\Shadow\miniconda3\lib\os.py", line 221, in makedirs
    mkdir(name, mode)
NotADirectoryError: [WinError 267] Der Verzeichnisname ist ungültig: '.\\Level 0: Cat Group'

````

Can you please help me with the issue?

**Comment by felixbiessmann** [comment]
hm, this looks like the column name, which is used for saving the model and log files, is not a valid directory name on your operating system. 

Unfortunately I don't have access to a windows machine. But could you try renaming the column to something without blanks, like maybe ``Level-0-Cat-Group``?

**Comment by TizianFusser** [comment]
Unfortunately, I got the same error after changing the column names.
I tried different windows machines and got different errors: One was the error mentioned above, the other error was this one: https://github.com/awslabs/datawig/issues/127

**Comment by felixbiessmann** [comment]
Hm, that's strange, if you changed the column name the error should include the new column name, can you share that new error message and ideally also the code that led to the error?

**Comment by TizianFusser** [comment]
I did not make any changes on the code:

```
import datawig, numpy
import pandas as pd

df = pd.read_csv('SpendCubeCleanNANsafespot.csv',low_memory=False)
df_imp= datawig.SimpleImputer.complete(df)

df_imp.to_csv('SpendCubeCleanDataWig.csv')
```


This is the error message:

```
Traceback` (most recent call last):
  File "C:/Users/tizia/PycharmProjects/untitled/complete2.py", line 5, in <module>
    df_imp= datawig.SimpleImputer.complete(df)
  File "C:\Users\tizia\PycharmProjects\untitled\venv\lib\site-packages\datawig\simple_imputer.py", line 524, in complete
    imputer.fit(data_frame.loc[~idx_missing, :],
  File "C:\Users\tizia\PycharmProjects\untitled\venv\lib\site-packages\datawig\simple_imputer.py", line 379, in fit
    self.imputer = Imputer(data_encoders=data_encoders,
  File "C:\Users\tizia\PycharmProjects\untitled\venv\lib\site-packages\datawig\imputer.py", line 150, in __init__
    os.makedirs(self.output_path)
  File "C:\Users\tizia\AppData\Local\Programs\Python\Python38\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
NotADirectoryError: [WinError 267] Der Verzeichnisname ist ungültig: '.\\Level_1:_Category'
```

**Comment by iamsteps** [comment]
Looks the like the problem with the directory name is with the colon, which is a [reserved character](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file) on Windows systems. Removal of this character should help.  
Ideally, Datawig would need to handle this in the library depending on the underlying OS.

**Comment by TizianFusser** [comment]
Thank you for the fast answer! I removed all restricted characters from the column names. It is working properly now.
